[package]
name = "roguewasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.219"
serde_derive = "1.0.219"

[dependencies.wasm-bindgen]
version = "^0.2"
features = ["serde-serialize"]
